name: update blogs

on:
  discussion:
    types: [created, edited]

jobs:
  webhook:
    runs-on: windows-latest
    steps:
      - name: update blogs
        run: |
          curl -X POST ${{ secrets.DEPLOY_HOOK }}
