name: Deploy on Discussion Create

on:
  discussion:
    types: [created, edited, deleted]

jobs:
  webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel deploy webhook
        run: |
          curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_aSAjqHlmUAQ5Qc4dIfflnwGfOld3/5WUoBy1LSS
